[package]
name = "rust-wfc"
version = "0.1.0"
authors = ["Chris McDonald <mail.chris.mcdonald@gmail.com>"]

[dependencies]
png = "0.6.2"
bit-vec = "0.4.3"
ndarray = "0.9.0"
rand = "0.3.15"
ordered-float = "0.4.0"
